// This file is automatically generated by qtc from "base-left.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line api/server/templates/base-left.qtpl:1
package templates

//line api/server/templates/base-left.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line api/server/templates/base-left.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line api/server/templates/base-left.qtpl:1
func (p *BasePage) StreamNavLeft(qw422016 *qt422016.Writer) {
	//line api/server/templates/base-left.qtpl:1
	qw422016.N().S(`
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    `)
	//line api/server/templates/base-left.qtpl:5
	if p.NavHeader {
		//line api/server/templates/base-left.qtpl:5
		qw422016.N().S(`
                    <li class="nav-header">
                        <div class="dropdown profile-element"> <span>
                            <img alt="image" class="img-circle" src="/static/img/profile_small.jpg" />
                             </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">David Williams</strong>
                             </span> <span class="text-muted text-xs block">Art Director <b class="caret"></b></span> </span> </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="profile.html">Profile</a></li>
                                <li><a href="contacts.html">Contacts</a></li>
                                <li><a href="mailbox.html">Mailbox</a></li>
                                <li class="divider"></li>
                                <li><a href="login.html">Logout</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            IN+
                        </div>
                    </li>
                    `)
		//line api/server/templates/base-left.qtpl:25
	}
	//line api/server/templates/base-left.qtpl:25
	qw422016.N().S(`
                    `)
	//line api/server/templates/base-left.qtpl:26
	for _, section := range p.NavSections {
		//line api/server/templates/base-left.qtpl:26
		qw422016.N().S(`
                    <li `)
		//line api/server/templates/base-left.qtpl:27
		if section.Active {
			//line api/server/templates/base-left.qtpl:27
			qw422016.N().S(`class="active"`)
			//line api/server/templates/base-left.qtpl:27
		}
		//line api/server/templates/base-left.qtpl:27
		qw422016.N().S(`>
                        <a href="index.html"><i class="fa fa-`)
		//line api/server/templates/base-left.qtpl:28
		qw422016.E().S(section.Icon)
		//line api/server/templates/base-left.qtpl:28
		qw422016.N().S(`"></i> <span class="nav-label">`)
		//line api/server/templates/base-left.qtpl:28
		qw422016.E().S(section.Title)
		//line api/server/templates/base-left.qtpl:28
		qw422016.N().S(`</span> <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            `)
		//line api/server/templates/base-left.qtpl:30
		for _, link := range section.NavLinks {
			//line api/server/templates/base-left.qtpl:30
			qw422016.N().S(`
                            <li `)
			//line api/server/templates/base-left.qtpl:31
			if link.Active {
				//line api/server/templates/base-left.qtpl:31
				qw422016.N().S(`class="active"`)
				//line api/server/templates/base-left.qtpl:31
			}
			//line api/server/templates/base-left.qtpl:31
			qw422016.N().S(`><a href="`)
			//line api/server/templates/base-left.qtpl:31
			qw422016.E().S(link.Href)
			//line api/server/templates/base-left.qtpl:31
			qw422016.N().S(`">`)
			//line api/server/templates/base-left.qtpl:31
			qw422016.E().S(link.Title)
			//line api/server/templates/base-left.qtpl:31
			qw422016.N().S(`</a></li>
                            `)
			//line api/server/templates/base-left.qtpl:32
		}
		//line api/server/templates/base-left.qtpl:32
		qw422016.N().S(`
                        </ul>
                    </li>
                    `)
		//line api/server/templates/base-left.qtpl:35
	}
	//line api/server/templates/base-left.qtpl:35
	qw422016.N().S(`
            </div>
        </nav>
`)
//line api/server/templates/base-left.qtpl:38
}

//line api/server/templates/base-left.qtpl:38
func (p *BasePage) WriteNavLeft(qq422016 qtio422016.Writer) {
	//line api/server/templates/base-left.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/base-left.qtpl:38
	p.StreamNavLeft(qw422016)
	//line api/server/templates/base-left.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/base-left.qtpl:38
}

//line api/server/templates/base-left.qtpl:38
func (p *BasePage) NavLeft() string {
	//line api/server/templates/base-left.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/base-left.qtpl:38
	p.WriteNavLeft(qb422016)
	//line api/server/templates/base-left.qtpl:38
	qs422016 := string(qb422016.B)
	//line api/server/templates/base-left.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/base-left.qtpl:38
	return qs422016
//line api/server/templates/base-left.qtpl:38
}
