// This file is automatically generated by qtc from "base-page.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line api/server/templates/base-page.qtpl:1
package templates

//line api/server/templates/base-page.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line api/server/templates/base-page.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line api/server/templates/base-page.qtpl:1
func StreamPageTemplate(qw422016 *qt422016.Writer, p *BasePage) {
	//line api/server/templates/base-page.qtpl:1
	qw422016.N().S(`
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>`)
	//line api/server/templates/base-page.qtpl:11
	qw422016.E().S(p.Title)
	//line api/server/templates/base-page.qtpl:11
	qw422016.N().S(`</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Toastr style -->
    <link href="/static/css/plugins/toastr/toastr.min.css" rel="stylesheet">

    <!-- Gritter -->
    <link href="/static/js/plugins/gritter/jquery.gritter.css" rel="stylesheet">

    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
</head>

<body class="top-navigation">
    <div id="wrapper">
        <div id="page-wrapper" class="gray-bg">
            `)
	//line api/server/templates/base-page.qtpl:29
	p.StreamNavTop(qw422016)
	//line api/server/templates/base-page.qtpl:29
	qw422016.N().S(`
            <div class="wrapper wrapper-content">
                <div class="container">
                `)
	//line api/server/templates/base-page.qtpl:32
	if p.Body == nil {
		//line api/server/templates/base-page.qtpl:32
		qw422016.N().S(`
                    BasePage.Body is unset
                `)
		//line api/server/templates/base-page.qtpl:34
	} else {
		//line api/server/templates/base-page.qtpl:34
		qw422016.N().S(`
                    `)
		//line api/server/templates/base-page.qtpl:35
		p.Body.StreamHTML(qw422016)
		//line api/server/templates/base-page.qtpl:35
		qw422016.N().S(`
                `)
		//line api/server/templates/base-page.qtpl:36
	}
	//line api/server/templates/base-page.qtpl:36
	qw422016.N().S(`
                </div> <!-- /container -->

            </div> <!-- /wrapper -->
        </div> <!-- /page-wrapper -->
    </div> <!-- wrapper -->

    <!-- Mainly scripts -->
    <script src="/static/js/jquery-3.1.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/static/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="/static/js/inspinia.js"></script>

    <!-- jQuery UI -->
    <script src="/static/js/plugins/jquery-ui/jquery-ui.min.js"></script>
</body>
</html>
`)
//line api/server/templates/base-page.qtpl:56
}

//line api/server/templates/base-page.qtpl:56
func WritePageTemplate(qq422016 qtio422016.Writer, p *BasePage) {
	//line api/server/templates/base-page.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/base-page.qtpl:56
	StreamPageTemplate(qw422016, p)
	//line api/server/templates/base-page.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/base-page.qtpl:56
}

//line api/server/templates/base-page.qtpl:56
func PageTemplate(p *BasePage) string {
	//line api/server/templates/base-page.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/base-page.qtpl:56
	WritePageTemplate(qb422016, p)
	//line api/server/templates/base-page.qtpl:56
	qs422016 := string(qb422016.B)
	//line api/server/templates/base-page.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/base-page.qtpl:56
	return qs422016
//line api/server/templates/base-page.qtpl:56
}
