// This file is automatically generated by qtc from "base-top.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line api/server/templates/base-top.qtpl:1
package templates

//line api/server/templates/base-top.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line api/server/templates/base-top.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line api/server/templates/base-top.qtpl:1
func (p *BasePage) StreamNavTop(qw422016 *qt422016.Writer) {
	//line api/server/templates/base-top.qtpl:1
	qw422016.N().S(`
    <div class="row border-bottom white-bg">
        <nav class="navbar navbar-static-top" role="navigation">
            <div class="navbar-header">
                <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                    <i class="fa fa-reorder"></i>
                </button>
                <a href="#" class="navbar-brand">Home</a>
            </div>
            <div class="navbar-collapse collapse" id="navbar">
                <ul class="nav navbar-nav">
                    `)
	//line api/server/templates/base-top.qtpl:12
	for _, section := range p.NavSections {
		//line api/server/templates/base-top.qtpl:12
		qw422016.N().S(`
                    <li class="dropdown">
                        <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown">`)
		//line api/server/templates/base-top.qtpl:14
		qw422016.E().S(section.Title)
		//line api/server/templates/base-top.qtpl:14
		qw422016.N().S(`<span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            `)
		//line api/server/templates/base-top.qtpl:16
		for _, link := range section.NavLinks {
			//line api/server/templates/base-top.qtpl:16
			qw422016.N().S(`
                            <li><a href="`)
			//line api/server/templates/base-top.qtpl:17
			qw422016.E().S(link.Href)
			//line api/server/templates/base-top.qtpl:17
			qw422016.N().S(`">`)
			//line api/server/templates/base-top.qtpl:17
			qw422016.E().S(link.Title)
			//line api/server/templates/base-top.qtpl:17
			qw422016.N().S(`</a></li>
                            `)
			//line api/server/templates/base-top.qtpl:18
		}
		//line api/server/templates/base-top.qtpl:18
		qw422016.N().S(`
                        </ul>
                    </li>
                    `)
		//line api/server/templates/base-top.qtpl:21
	}
	//line api/server/templates/base-top.qtpl:21
	qw422016.N().S(`
                    </li>
                </ul>
            </div>
        </nav>
    </div>
`)
//line api/server/templates/base-top.qtpl:27
}

//line api/server/templates/base-top.qtpl:27
func (p *BasePage) WriteNavTop(qq422016 qtio422016.Writer) {
	//line api/server/templates/base-top.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/base-top.qtpl:27
	p.StreamNavTop(qw422016)
	//line api/server/templates/base-top.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/base-top.qtpl:27
}

//line api/server/templates/base-top.qtpl:27
func (p *BasePage) NavTop() string {
	//line api/server/templates/base-top.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/base-top.qtpl:27
	p.WriteNavTop(qb422016)
	//line api/server/templates/base-top.qtpl:27
	qs422016 := string(qb422016.B)
	//line api/server/templates/base-top.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/base-top.qtpl:27
	return qs422016
//line api/server/templates/base-top.qtpl:27
}
