// This file is automatically generated by qtc from "body.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line api/server/templates/body.qtpl:2
package templates

//line api/server/templates/body.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line api/server/templates/body.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line api/server/templates/body.qtpl:2
type Body interface {
	//line api/server/templates/body.qtpl:2
	HTML() string
	//line api/server/templates/body.qtpl:2
	StreamHTML(qw422016 *qt422016.Writer)
	//line api/server/templates/body.qtpl:2
	WriteHTML(qq422016 qtio422016.Writer)
//line api/server/templates/body.qtpl:2
}
