// This file is automatically generated by qtc from "rows.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line api/server/templates/rows.qtpl:1
package templates

//line api/server/templates/rows.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line api/server/templates/rows.qtpl:1
import "github.com/AdamJacobMuller/home-api/api/models"

//line api/server/templates/rows.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line api/server/templates/rows.qtpl:3
type Rows struct {
	Rows []Row
}

func (r *Rows) AddRow(row Row) {
	r.Rows = append(r.Rows, row)
}

type GenericRow struct {
	Boxes []Box
}
type GenericBox struct {
	Title string
}
type Action struct {
	Title string
}
type ChildDeviceBox struct {
	Title   string
	Actions []*Action
}
type DimmableSwitchBox struct {
	Title      string
	ProviderID string
	DeviceID   string
	Device     *apimodels.Device
}
type RedEyeBox struct {
	Title      string
	ProviderID string
	DeviceID   string
	Device     *apimodels.Device
	Actions    []*Action
}

func (b *RedEyeBox) AddAction(action *Action) {
	b.Actions = append(b.Actions, action)
}

type BinarySwitchBox struct {
	Title      string
	ProviderID string
	DeviceID   string
	Device     *apimodels.Device
}
type DoorLockBox struct {
	Title      string
	ProviderID string
	DeviceID   string
	Device     *apimodels.Device
}
type ColorChangeBulbBox struct {
	Title            string
	ProviderID       string
	DeviceID         string
	Device           *apimodels.Device
	PowerControlRoot bool
}
type SonosBox struct {
	Title      string
	ProviderID string
	DeviceID   string
	Device     *apimodels.Device
}
type TivoBox struct {
	Title      string
	ProviderID string
	DeviceID   string
	Device     *apimodels.Device
}
type DeviceBox struct {
	Title      string
	ProviderID string
	DeviceID   string
	Device     *apimodels.Device
	Actions    []*Action
	Children   []*ChildDeviceBox
}

func (b *DeviceBox) AddChild(child *ChildDeviceBox) {
	b.Children = append(b.Children, child)
}
func (b *ChildDeviceBox) AddAction(action *Action) {
	b.Actions = append(b.Actions, action)
}
func (b *DeviceBox) AddAction(action *Action) {
	b.Actions = append(b.Actions, action)
}
func (r *GenericRow) AddBox(box Box) {
	r.Boxes = append(r.Boxes, box)
}

//line api/server/templates/rows.qtpl:92
type Row interface {
	//line api/server/templates/rows.qtpl:92
	HTML() string
	//line api/server/templates/rows.qtpl:92
	StreamHTML(qw422016 *qt422016.Writer)
	//line api/server/templates/rows.qtpl:92
	WriteHTML(qq422016 qtio422016.Writer)
//line api/server/templates/rows.qtpl:92
}

//line api/server/templates/rows.qtpl:97
type Box interface {
	//line api/server/templates/rows.qtpl:97
	HTML() string
	//line api/server/templates/rows.qtpl:97
	StreamHTML(qw422016 *qt422016.Writer)
	//line api/server/templates/rows.qtpl:97
	WriteHTML(qq422016 qtio422016.Writer)
//line api/server/templates/rows.qtpl:97
}

//line api/server/templates/rows.qtpl:103
func (p Rows) StreamHTML(qw422016 *qt422016.Writer) {
	//line api/server/templates/rows.qtpl:103
	qw422016.N().S(`
    `)
	//line api/server/templates/rows.qtpl:104
	for _, r := range p.Rows {
		//line api/server/templates/rows.qtpl:104
		qw422016.N().S(`
        `)
		//line api/server/templates/rows.qtpl:105
		r.StreamHTML(qw422016)
		//line api/server/templates/rows.qtpl:105
		qw422016.N().S(`
    `)
		//line api/server/templates/rows.qtpl:106
	}
	//line api/server/templates/rows.qtpl:106
	qw422016.N().S(`
`)
//line api/server/templates/rows.qtpl:107
}

//line api/server/templates/rows.qtpl:107
func (p Rows) WriteHTML(qq422016 qtio422016.Writer) {
	//line api/server/templates/rows.qtpl:107
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:107
	p.StreamHTML(qw422016)
	//line api/server/templates/rows.qtpl:107
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:107
}

//line api/server/templates/rows.qtpl:107
func (p Rows) HTML() string {
	//line api/server/templates/rows.qtpl:107
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:107
	p.WriteHTML(qb422016)
	//line api/server/templates/rows.qtpl:107
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:107
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:107
	return qs422016
//line api/server/templates/rows.qtpl:107
}

//line api/server/templates/rows.qtpl:110
func (p GenericRow) StreamHTML(qw422016 *qt422016.Writer) {
	//line api/server/templates/rows.qtpl:110
	qw422016.N().S(`
<div class="row wrapper wrapper-content animated fadeInRight">
    `)
	//line api/server/templates/rows.qtpl:112
	for _, b := range p.Boxes {
		//line api/server/templates/rows.qtpl:112
		qw422016.N().S(`
        <div class="col-lg-3 col-sm-6 col-md-6 grid-item">
            <div class="ibox float-e-margins">
                `)
		//line api/server/templates/rows.qtpl:115
		b.StreamHTML(qw422016)
		//line api/server/templates/rows.qtpl:115
		qw422016.N().S(`
            </div>
        </div>
    `)
		//line api/server/templates/rows.qtpl:118
	}
	//line api/server/templates/rows.qtpl:118
	qw422016.N().S(`
</div>
`)
//line api/server/templates/rows.qtpl:120
}

//line api/server/templates/rows.qtpl:120
func (p GenericRow) WriteHTML(qq422016 qtio422016.Writer) {
	//line api/server/templates/rows.qtpl:120
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:120
	p.StreamHTML(qw422016)
	//line api/server/templates/rows.qtpl:120
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:120
}

//line api/server/templates/rows.qtpl:120
func (p GenericRow) HTML() string {
	//line api/server/templates/rows.qtpl:120
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:120
	p.WriteHTML(qb422016)
	//line api/server/templates/rows.qtpl:120
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:120
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:120
	return qs422016
//line api/server/templates/rows.qtpl:120
}

//line api/server/templates/rows.qtpl:121
func (b GenericBox) StreamHTML(qw422016 *qt422016.Writer) {
	//line api/server/templates/rows.qtpl:121
	qw422016.N().S(`
<div class="ibox-title">
    <h5>`)
	//line api/server/templates/rows.qtpl:123
	qw422016.E().S(b.Title)
	//line api/server/templates/rows.qtpl:123
	qw422016.N().S(`</h5>
    <div class="ibox-tools">
        <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
        </a>
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-wrench"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li><a href="#">Config option 1</a>
            </li>
            <li><a href="#">Config option 2</a>
            </li>
        </ul>
        <a class="close-link">
            <i class="fa fa-times"></i>
        </a>
    </div>
</div>
<div class="ibox-content">
    <p>
        Use any of the available button classes to quickly create a styled button.
    </p>

    <h3 class="font-bold">
        Normal buttons
    </h3>
    <p>
        <button type="button" class="btn btn-w-m btn-default">Default</button>
        <button type="button" class="btn btn-w-m btn-primary">Primary</button>
        <button type="button" class="btn btn-w-m btn-success">Success</button>
        <button type="button" class="btn btn-w-m btn-info">Info</button>
        <button type="button" class="btn btn-w-m btn-warning">Warning</button>
        <button type="button" class="btn btn-w-m btn-danger">Danger</button>
        <button type="button" class="btn btn-w-m btn-link">Link</button>
    </p>
</div>
`)
//line api/server/templates/rows.qtpl:160
}

//line api/server/templates/rows.qtpl:160
func (b GenericBox) WriteHTML(qq422016 qtio422016.Writer) {
	//line api/server/templates/rows.qtpl:160
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:160
	b.StreamHTML(qw422016)
	//line api/server/templates/rows.qtpl:160
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:160
}

//line api/server/templates/rows.qtpl:160
func (b GenericBox) HTML() string {
	//line api/server/templates/rows.qtpl:160
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:160
	b.WriteHTML(qb422016)
	//line api/server/templates/rows.qtpl:160
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:160
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:160
	return qs422016
//line api/server/templates/rows.qtpl:160
}

//line api/server/templates/rows.qtpl:162
func (b BinarySwitchBox) StreamHTML(qw422016 *qt422016.Writer) {
	//line api/server/templates/rows.qtpl:162
	qw422016.N().S(`
<div class="ibox-title">
    <h5>`)
	//line api/server/templates/rows.qtpl:164
	qw422016.E().S(b.Title)
	//line api/server/templates/rows.qtpl:164
	qw422016.N().S(`</h5>
    <div class="ibox-tools">
        <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>
</div>
<div class="ibox-content">
<p>
    <button class="btn btn-primary btn-large-dim" type="button" `)
	//line api/server/templates/rows.qtpl:173
	StreamOnClickSetDeviceValue(qw422016, b.ProviderID, b.DeviceID, 255)
	//line api/server/templates/rows.qtpl:173
	qw422016.N().S(`><i class="fa fa-power-off"></i></button>
    <button class="btn btn-danger btn-large-dim" type="button" `)
	//line api/server/templates/rows.qtpl:174
	StreamOnClickSetDeviceValue(qw422016, b.ProviderID, b.DeviceID, 0)
	//line api/server/templates/rows.qtpl:174
	qw422016.N().S(`><i class="fa fa-power-off"></i></button>
</p>
</div>
`)
//line api/server/templates/rows.qtpl:177
}

//line api/server/templates/rows.qtpl:177
func (b BinarySwitchBox) WriteHTML(qq422016 qtio422016.Writer) {
	//line api/server/templates/rows.qtpl:177
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:177
	b.StreamHTML(qw422016)
	//line api/server/templates/rows.qtpl:177
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:177
}

//line api/server/templates/rows.qtpl:177
func (b BinarySwitchBox) HTML() string {
	//line api/server/templates/rows.qtpl:177
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:177
	b.WriteHTML(qb422016)
	//line api/server/templates/rows.qtpl:177
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:177
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:177
	return qs422016
//line api/server/templates/rows.qtpl:177
}

//line api/server/templates/rows.qtpl:178
func (b DimmableSwitchBox) StreamHTML(qw422016 *qt422016.Writer) {
	//line api/server/templates/rows.qtpl:178
	qw422016.N().S(`
<div class="ibox-title">
    <h5>`)
	//line api/server/templates/rows.qtpl:180
	qw422016.E().S(b.Title)
	//line api/server/templates/rows.qtpl:180
	qw422016.N().S(`</h5>
    <div class="ibox-tools">
        <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>
</div>
<div class="ibox-content">
    <p>
        <button class="btn btn-primary btn-large-dim" type="button" `)
	//line api/server/templates/rows.qtpl:189
	StreamOnClickSetDeviceValue(qw422016, b.ProviderID, b.DeviceID, 255)
	//line api/server/templates/rows.qtpl:189
	qw422016.N().S(`><i class="fa fa-power-off"></i></button>
        <button class="btn btn-danger btn-large-dim" type="button" `)
	//line api/server/templates/rows.qtpl:190
	StreamOnClickSetDeviceValue(qw422016, b.ProviderID, b.DeviceID, 0)
	//line api/server/templates/rows.qtpl:190
	qw422016.N().S(`><i class="fa fa-power-off"></i></button>
    </p>
    <p>
        <button class="btn btn-default" type="button" `)
	//line api/server/templates/rows.qtpl:193
	StreamOnClickSetDeviceValue(qw422016, b.ProviderID, b.DeviceID, 1)
	//line api/server/templates/rows.qtpl:193
	qw422016.N().S(`>1%</button>
        <button class="btn btn-default" type="button" `)
	//line api/server/templates/rows.qtpl:194
	StreamOnClickSetDeviceValue(qw422016, b.ProviderID, b.DeviceID, 10)
	//line api/server/templates/rows.qtpl:194
	qw422016.N().S(`>10%</button>
        <button class="btn btn-default" type="button" `)
	//line api/server/templates/rows.qtpl:195
	StreamOnClickSetDeviceValue(qw422016, b.ProviderID, b.DeviceID, 25)
	//line api/server/templates/rows.qtpl:195
	qw422016.N().S(`>25%</button>
        <button class="btn btn-default" type="button" `)
	//line api/server/templates/rows.qtpl:196
	StreamOnClickSetDeviceValue(qw422016, b.ProviderID, b.DeviceID, 50)
	//line api/server/templates/rows.qtpl:196
	qw422016.N().S(`>50%</button>
        <button class="btn btn-default" type="button" `)
	//line api/server/templates/rows.qtpl:197
	StreamOnClickSetDeviceValue(qw422016, b.ProviderID, b.DeviceID, 75)
	//line api/server/templates/rows.qtpl:197
	qw422016.N().S(`>75%</button>
        <button class="btn btn-default" type="button" `)
	//line api/server/templates/rows.qtpl:198
	StreamOnClickSetDeviceValue(qw422016, b.ProviderID, b.DeviceID, 100)
	//line api/server/templates/rows.qtpl:198
	qw422016.N().S(`>100%</button>
    </p>
</div>
`)
//line api/server/templates/rows.qtpl:201
}

//line api/server/templates/rows.qtpl:201
func (b DimmableSwitchBox) WriteHTML(qq422016 qtio422016.Writer) {
	//line api/server/templates/rows.qtpl:201
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:201
	b.StreamHTML(qw422016)
	//line api/server/templates/rows.qtpl:201
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:201
}

//line api/server/templates/rows.qtpl:201
func (b DimmableSwitchBox) HTML() string {
	//line api/server/templates/rows.qtpl:201
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:201
	b.WriteHTML(qb422016)
	//line api/server/templates/rows.qtpl:201
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:201
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:201
	return qs422016
//line api/server/templates/rows.qtpl:201
}

//line api/server/templates/rows.qtpl:202
func StreamOnClickSetDeviceValue(qw422016 *qt422016.Writer, ProviderID string, DeviceID string, value int) {
	//line api/server/templates/rows.qtpl:202
	qw422016.N().S(`
onclick="$.ajax({type: 'POST', url: '/api/SetDevicesValue', data: JSON.stringify({'match':{ProviderID: '`)
	//line api/server/templates/rows.qtpl:203
	qw422016.E().S(ProviderID)
	//line api/server/templates/rows.qtpl:203
	qw422016.N().S(`', DeviceID: '`)
	//line api/server/templates/rows.qtpl:203
	qw422016.E().S(DeviceID)
	//line api/server/templates/rows.qtpl:203
	qw422016.N().S(`'}, value: `)
	//line api/server/templates/rows.qtpl:203
	qw422016.N().D(value)
	//line api/server/templates/rows.qtpl:203
	qw422016.N().S(`}), success: function(data){console.log(data);}, dataType: 'json'});"
`)
//line api/server/templates/rows.qtpl:204
}

//line api/server/templates/rows.qtpl:204
func WriteOnClickSetDeviceValue(qq422016 qtio422016.Writer, ProviderID string, DeviceID string, value int) {
	//line api/server/templates/rows.qtpl:204
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:204
	StreamOnClickSetDeviceValue(qw422016, ProviderID, DeviceID, value)
	//line api/server/templates/rows.qtpl:204
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:204
}

//line api/server/templates/rows.qtpl:204
func OnClickSetDeviceValue(ProviderID string, DeviceID string, value int) string {
	//line api/server/templates/rows.qtpl:204
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:204
	WriteOnClickSetDeviceValue(qb422016, ProviderID, DeviceID, value)
	//line api/server/templates/rows.qtpl:204
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:204
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:204
	return qs422016
//line api/server/templates/rows.qtpl:204
}

//line api/server/templates/rows.qtpl:205
func StreamOnClickInvokeDeviceAction(qw422016 *qt422016.Writer, ProviderID string, DeviceID string, action string) {
	//line api/server/templates/rows.qtpl:205
	qw422016.N().S(`
onclick="$.ajax({type: 'POST', url: '/api/InvokeDevicesAction', data: JSON.stringify({'match':{ProviderID: '`)
	//line api/server/templates/rows.qtpl:206
	qw422016.E().S(ProviderID)
	//line api/server/templates/rows.qtpl:206
	qw422016.N().S(`', DeviceID: '`)
	//line api/server/templates/rows.qtpl:206
	qw422016.E().S(DeviceID)
	//line api/server/templates/rows.qtpl:206
	qw422016.N().S(`'}, action: '`)
	//line api/server/templates/rows.qtpl:206
	qw422016.E().S(action)
	//line api/server/templates/rows.qtpl:206
	qw422016.N().S(`'}), success: function(data){console.log(data);}, dataType: 'json'});"
`)
//line api/server/templates/rows.qtpl:207
}

//line api/server/templates/rows.qtpl:207
func WriteOnClickInvokeDeviceAction(qq422016 qtio422016.Writer, ProviderID string, DeviceID string, action string) {
	//line api/server/templates/rows.qtpl:207
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:207
	StreamOnClickInvokeDeviceAction(qw422016, ProviderID, DeviceID, action)
	//line api/server/templates/rows.qtpl:207
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:207
}

//line api/server/templates/rows.qtpl:207
func OnClickInvokeDeviceAction(ProviderID string, DeviceID string, action string) string {
	//line api/server/templates/rows.qtpl:207
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:207
	WriteOnClickInvokeDeviceAction(qb422016, ProviderID, DeviceID, action)
	//line api/server/templates/rows.qtpl:207
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:207
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:207
	return qs422016
//line api/server/templates/rows.qtpl:207
}

//line api/server/templates/rows.qtpl:208
func StreamOnClickSetChildDeviceValue(qw422016 *qt422016.Writer, ProviderID string, DeviceID string, ChildName string, value int) {
	//line api/server/templates/rows.qtpl:208
	qw422016.N().S(`
onclick="$.ajax({type: 'POST', url: '/api/SetChildDevicesValue', data: JSON.stringify({match:{ProviderID: '`)
	//line api/server/templates/rows.qtpl:209
	qw422016.E().S(ProviderID)
	//line api/server/templates/rows.qtpl:209
	qw422016.N().S(`', DeviceID: '`)
	//line api/server/templates/rows.qtpl:209
	qw422016.E().S(DeviceID)
	//line api/server/templates/rows.qtpl:209
	qw422016.N().S(`', Child: {Name: '`)
	//line api/server/templates/rows.qtpl:209
	qw422016.E().S(ChildName)
	//line api/server/templates/rows.qtpl:209
	qw422016.N().S(`'}}, value: `)
	//line api/server/templates/rows.qtpl:209
	qw422016.N().D(value)
	//line api/server/templates/rows.qtpl:209
	qw422016.N().S(`}), success: function(data){console.log(data);}, dataType: 'json'});"
`)
//line api/server/templates/rows.qtpl:210
}

//line api/server/templates/rows.qtpl:210
func WriteOnClickSetChildDeviceValue(qq422016 qtio422016.Writer, ProviderID string, DeviceID string, ChildName string, value int) {
	//line api/server/templates/rows.qtpl:210
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:210
	StreamOnClickSetChildDeviceValue(qw422016, ProviderID, DeviceID, ChildName, value)
	//line api/server/templates/rows.qtpl:210
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:210
}

//line api/server/templates/rows.qtpl:210
func OnClickSetChildDeviceValue(ProviderID string, DeviceID string, ChildName string, value int) string {
	//line api/server/templates/rows.qtpl:210
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:210
	WriteOnClickSetChildDeviceValue(qb422016, ProviderID, DeviceID, ChildName, value)
	//line api/server/templates/rows.qtpl:210
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:210
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:210
	return qs422016
//line api/server/templates/rows.qtpl:210
}

//line api/server/templates/rows.qtpl:211
func StreamOnClickInvokeChildDeviceAction(qw422016 *qt422016.Writer, ProviderID string, DeviceID string, ChildName string, action string) {
	//line api/server/templates/rows.qtpl:211
	qw422016.N().S(`
onclick="$.ajax({type: 'POST', url: '/api/InvokeChildDevicesAction', data: JSON.stringify({match:{ProviderID: '`)
	//line api/server/templates/rows.qtpl:212
	qw422016.E().S(ProviderID)
	//line api/server/templates/rows.qtpl:212
	qw422016.N().S(`', DeviceID: '`)
	//line api/server/templates/rows.qtpl:212
	qw422016.E().S(DeviceID)
	//line api/server/templates/rows.qtpl:212
	qw422016.N().S(`', Child: {Name: '`)
	//line api/server/templates/rows.qtpl:212
	qw422016.E().S(ChildName)
	//line api/server/templates/rows.qtpl:212
	qw422016.N().S(`'}}, action: '`)
	//line api/server/templates/rows.qtpl:212
	qw422016.E().S(action)
	//line api/server/templates/rows.qtpl:212
	qw422016.N().S(`'}), success: function(data){console.log(data);}, dataType: 'json'});"
`)
//line api/server/templates/rows.qtpl:213
}

//line api/server/templates/rows.qtpl:213
func WriteOnClickInvokeChildDeviceAction(qq422016 qtio422016.Writer, ProviderID string, DeviceID string, ChildName string, action string) {
	//line api/server/templates/rows.qtpl:213
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:213
	StreamOnClickInvokeChildDeviceAction(qw422016, ProviderID, DeviceID, ChildName, action)
	//line api/server/templates/rows.qtpl:213
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:213
}

//line api/server/templates/rows.qtpl:213
func OnClickInvokeChildDeviceAction(ProviderID string, DeviceID string, ChildName string, action string) string {
	//line api/server/templates/rows.qtpl:213
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:213
	WriteOnClickInvokeChildDeviceAction(qb422016, ProviderID, DeviceID, ChildName, action)
	//line api/server/templates/rows.qtpl:213
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:213
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:213
	return qs422016
//line api/server/templates/rows.qtpl:213
}

//line api/server/templates/rows.qtpl:214
func (b ColorChangeBulbBox) StreamHTML(qw422016 *qt422016.Writer) {
	//line api/server/templates/rows.qtpl:214
	qw422016.N().S(`
                    <div class="ibox-title">
                        <h5>`)
	//line api/server/templates/rows.qtpl:216
	qw422016.E().S(b.Title)
	//line api/server/templates/rows.qtpl:216
	qw422016.N().S(`</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                    <p>
                    `)
	//line api/server/templates/rows.qtpl:225
	if b.PowerControlRoot {
		//line api/server/templates/rows.qtpl:225
		qw422016.N().S(`
                        <button class="btn btn-primary btn-large-dim" type="button" `)
		//line api/server/templates/rows.qtpl:226
		StreamOnClickInvokeDeviceAction(qw422016, b.ProviderID, b.DeviceID, "On")
		//line api/server/templates/rows.qtpl:226
		qw422016.N().S(`><i class="fa fa-power-off"></i></button>
                        <button class="btn btn-danger btn-large-dim" type="button" `)
		//line api/server/templates/rows.qtpl:227
		StreamOnClickInvokeDeviceAction(qw422016, b.ProviderID, b.DeviceID, "Off")
		//line api/server/templates/rows.qtpl:227
		qw422016.N().S(`><i class="fa fa-power-off"></i></button>
                    `)
		//line api/server/templates/rows.qtpl:228
	} else {
		//line api/server/templates/rows.qtpl:228
		qw422016.N().S(`
                        <button class="btn btn-primary btn-large-dim" type="button" `)
		//line api/server/templates/rows.qtpl:229
		StreamOnClickSetChildDeviceValue(qw422016, b.ProviderID, b.DeviceID, "Switch Multilevel", 255)
		//line api/server/templates/rows.qtpl:229
		qw422016.N().S(`><i class="fa fa-power-off"></i></button>
                        <button class="btn btn-danger btn-large-dim" type="button" `)
		//line api/server/templates/rows.qtpl:230
		StreamOnClickSetChildDeviceValue(qw422016, b.ProviderID, b.DeviceID, "Switch Multilevel", 0)
		//line api/server/templates/rows.qtpl:230
		qw422016.N().S(`><i class="fa fa-power-off"></i></button>
                    `)
		//line api/server/templates/rows.qtpl:231
	}
	//line api/server/templates/rows.qtpl:231
	qw422016.N().S(`
                    </p>
                    <p>
                        <button class="btn btn-danger" type="button" `)
	//line api/server/templates/rows.qtpl:234
	StreamOnClickInvokeDeviceAction(qw422016, b.ProviderID, b.DeviceID, "Red")
	//line api/server/templates/rows.qtpl:234
	qw422016.N().S(`>R</button>
                        <button class="btn btn-primary" type="button" `)
	//line api/server/templates/rows.qtpl:235
	StreamOnClickInvokeDeviceAction(qw422016, b.ProviderID, b.DeviceID, "Green")
	//line api/server/templates/rows.qtpl:235
	qw422016.N().S(`>G</button>
                        <button class="btn btn-success" type="button" `)
	//line api/server/templates/rows.qtpl:236
	StreamOnClickInvokeDeviceAction(qw422016, b.ProviderID, b.DeviceID, "Blue")
	//line api/server/templates/rows.qtpl:236
	qw422016.N().S(`>B</button>
                        <button class="btn btn-default" type="button" `)
	//line api/server/templates/rows.qtpl:237
	StreamOnClickInvokeDeviceAction(qw422016, b.ProviderID, b.DeviceID, "Cold White")
	//line api/server/templates/rows.qtpl:237
	qw422016.N().S(`>CW</button>
                        <button class="btn btn-default" type="button" `)
	//line api/server/templates/rows.qtpl:238
	StreamOnClickInvokeDeviceAction(qw422016, b.ProviderID, b.DeviceID, "Warm White")
	//line api/server/templates/rows.qtpl:238
	qw422016.N().S(`>WW</button>
                    </p>
                    </div>
`)
//line api/server/templates/rows.qtpl:241
}

//line api/server/templates/rows.qtpl:241
func (b ColorChangeBulbBox) WriteHTML(qq422016 qtio422016.Writer) {
	//line api/server/templates/rows.qtpl:241
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:241
	b.StreamHTML(qw422016)
	//line api/server/templates/rows.qtpl:241
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:241
}

//line api/server/templates/rows.qtpl:241
func (b ColorChangeBulbBox) HTML() string {
	//line api/server/templates/rows.qtpl:241
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:241
	b.WriteHTML(qb422016)
	//line api/server/templates/rows.qtpl:241
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:241
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:241
	return qs422016
//line api/server/templates/rows.qtpl:241
}

//line api/server/templates/rows.qtpl:242
func (b SonosBox) StreamHTML(qw422016 *qt422016.Writer) {
	//line api/server/templates/rows.qtpl:242
	qw422016.N().S(`
                    <div class="ibox-title">
                        <h5>`)
	//line api/server/templates/rows.qtpl:244
	qw422016.E().S(b.Title)
	//line api/server/templates/rows.qtpl:244
	qw422016.N().S(`</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                    <button class="btn btn-default btn-large-dim" type="button" `)
	//line api/server/templates/rows.qtpl:252
	StreamOnClickInvokeDeviceAction(qw422016, b.ProviderID, b.DeviceID, "Play")
	//line api/server/templates/rows.qtpl:252
	qw422016.N().S(`><i class="fa fa-play"></i></button>
                    <button class="btn btn-default btn-large-dim" type="button" `)
	//line api/server/templates/rows.qtpl:253
	StreamOnClickInvokeDeviceAction(qw422016, b.ProviderID, b.DeviceID, "Pause")
	//line api/server/templates/rows.qtpl:253
	qw422016.N().S(`><i class="fa fa-pause"></i></button>
                    <button class="btn btn-default btn-large-dim" type="button" `)
	//line api/server/templates/rows.qtpl:254
	StreamOnClickInvokeDeviceAction(qw422016, b.ProviderID, b.DeviceID, "Next")
	//line api/server/templates/rows.qtpl:254
	qw422016.N().S(`><i class="fa fa-step-forward"></i></button>
                    </div>
`)
//line api/server/templates/rows.qtpl:256
}

//line api/server/templates/rows.qtpl:256
func (b SonosBox) WriteHTML(qq422016 qtio422016.Writer) {
	//line api/server/templates/rows.qtpl:256
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:256
	b.StreamHTML(qw422016)
	//line api/server/templates/rows.qtpl:256
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:256
}

//line api/server/templates/rows.qtpl:256
func (b SonosBox) HTML() string {
	//line api/server/templates/rows.qtpl:256
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:256
	b.WriteHTML(qb422016)
	//line api/server/templates/rows.qtpl:256
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:256
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:256
	return qs422016
//line api/server/templates/rows.qtpl:256
}

//line api/server/templates/rows.qtpl:257
func (b TivoBox) StreamHTML(qw422016 *qt422016.Writer) {
	//line api/server/templates/rows.qtpl:257
	qw422016.N().S(`
                    <div class="ibox-title">
                        <h5>`)
	//line api/server/templates/rows.qtpl:259
	qw422016.E().S(b.Title)
	//line api/server/templates/rows.qtpl:259
	qw422016.N().S(`</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                    <button class="btn btn-default btn-large-dim" type="button"><i class="fa fa-apple"></i></button>
                    <button class="btn btn-default btn-large-dim" type="button"><i class="fa fa-github"></i></button>
                    <button class="btn btn-default btn-large-dim" type="button"><i class="fa fa-linux"></i></button>
                    <button class="btn btn-default btn-large-dim" type="button"><i class="fa fa-stack-overflow"></i></button>
                    </div>
`)
//line api/server/templates/rows.qtpl:272
}

//line api/server/templates/rows.qtpl:272
func (b TivoBox) WriteHTML(qq422016 qtio422016.Writer) {
	//line api/server/templates/rows.qtpl:272
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:272
	b.StreamHTML(qw422016)
	//line api/server/templates/rows.qtpl:272
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:272
}

//line api/server/templates/rows.qtpl:272
func (b TivoBox) HTML() string {
	//line api/server/templates/rows.qtpl:272
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:272
	b.WriteHTML(qb422016)
	//line api/server/templates/rows.qtpl:272
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:272
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:272
	return qs422016
//line api/server/templates/rows.qtpl:272
}

//line api/server/templates/rows.qtpl:274
func (b DoorLockBox) StreamHTML(qw422016 *qt422016.Writer) {
	//line api/server/templates/rows.qtpl:274
	qw422016.N().S(`
                    <div class="ibox-title">
                        <h5>`)
	//line api/server/templates/rows.qtpl:276
	qw422016.E().S(b.Title)
	//line api/server/templates/rows.qtpl:276
	qw422016.N().S(`</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                    <button class="btn btn-primary btn-large-dim" type="button" `)
	//line api/server/templates/rows.qtpl:284
	StreamOnClickInvokeChildDeviceAction(qw422016, b.ProviderID, b.DeviceID, "Lock", "Lock")
	//line api/server/templates/rows.qtpl:284
	qw422016.N().S(`><i class="fa fa-lock"></i></button>
                    <button class="btn btn-danger btn-large-dim" type="button" `)
	//line api/server/templates/rows.qtpl:285
	StreamOnClickInvokeChildDeviceAction(qw422016, b.ProviderID, b.DeviceID, "Lock", "Unlock")
	//line api/server/templates/rows.qtpl:285
	qw422016.N().S(`><i class="fa fa-unlock"></i></button>
                    </div>
`)
//line api/server/templates/rows.qtpl:287
}

//line api/server/templates/rows.qtpl:287
func (b DoorLockBox) WriteHTML(qq422016 qtio422016.Writer) {
	//line api/server/templates/rows.qtpl:287
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:287
	b.StreamHTML(qw422016)
	//line api/server/templates/rows.qtpl:287
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:287
}

//line api/server/templates/rows.qtpl:287
func (b DoorLockBox) HTML() string {
	//line api/server/templates/rows.qtpl:287
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:287
	b.WriteHTML(qb422016)
	//line api/server/templates/rows.qtpl:287
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:287
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:287
	return qs422016
//line api/server/templates/rows.qtpl:287
}

//line api/server/templates/rows.qtpl:288
func (b RedEyeBox) StreamHTML(qw422016 *qt422016.Writer) {
	//line api/server/templates/rows.qtpl:288
	qw422016.N().S(`
                    <div class="ibox-title">
                        <h5>`)
	//line api/server/templates/rows.qtpl:290
	qw422016.E().S(b.Title)
	//line api/server/templates/rows.qtpl:290
	qw422016.N().S(`</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <p>
                            `)
	//line api/server/templates/rows.qtpl:299
	for _, action := range b.Actions {
		//line api/server/templates/rows.qtpl:299
		qw422016.N().S(`
                                <button type="button" class="btn btn-w-m btn-default" `)
		//line api/server/templates/rows.qtpl:300
		StreamOnClickInvokeDeviceAction(qw422016, b.ProviderID, b.DeviceID, action.Title)
		//line api/server/templates/rows.qtpl:300
		qw422016.N().S(`>`)
		//line api/server/templates/rows.qtpl:300
		qw422016.E().S(action.Title)
		//line api/server/templates/rows.qtpl:300
		qw422016.N().S(`</button>
                            `)
		//line api/server/templates/rows.qtpl:301
	}
	//line api/server/templates/rows.qtpl:301
	qw422016.N().S(`
                        </p>
                    </div>
`)
//line api/server/templates/rows.qtpl:304
}

//line api/server/templates/rows.qtpl:304
func (b RedEyeBox) WriteHTML(qq422016 qtio422016.Writer) {
	//line api/server/templates/rows.qtpl:304
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:304
	b.StreamHTML(qw422016)
	//line api/server/templates/rows.qtpl:304
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:304
}

//line api/server/templates/rows.qtpl:304
func (b RedEyeBox) HTML() string {
	//line api/server/templates/rows.qtpl:304
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:304
	b.WriteHTML(qb422016)
	//line api/server/templates/rows.qtpl:304
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:304
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:304
	return qs422016
//line api/server/templates/rows.qtpl:304
}

//line api/server/templates/rows.qtpl:305
func (b DeviceBox) StreamHTML(qw422016 *qt422016.Writer) {
	//line api/server/templates/rows.qtpl:305
	qw422016.N().S(`
                    <div class="ibox-title">
                        <h5>`)
	//line api/server/templates/rows.qtpl:307
	qw422016.E().S(b.Title)
	//line api/server/templates/rows.qtpl:307
	qw422016.N().S(`</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <p>
                            `)
	//line api/server/templates/rows.qtpl:316
	for _, action := range b.Actions {
		//line api/server/templates/rows.qtpl:316
		qw422016.N().S(`
                                <button type="button" class="btn btn-w-m btn-default">`)
		//line api/server/templates/rows.qtpl:317
		qw422016.E().S(action.Title)
		//line api/server/templates/rows.qtpl:317
		qw422016.N().S(`</button>
                            `)
		//line api/server/templates/rows.qtpl:318
	}
	//line api/server/templates/rows.qtpl:318
	qw422016.N().S(`
                        </p>
                        `)
	//line api/server/templates/rows.qtpl:320
	for _, child := range b.Children {
		//line api/server/templates/rows.qtpl:320
		qw422016.N().S(`
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h5 class="panel-title">
                                        <a>`)
		//line api/server/templates/rows.qtpl:324
		qw422016.E().S(child.Title)
		//line api/server/templates/rows.qtpl:324
		qw422016.N().S(`</a>
                                    </h5>
                                </div>
                                <div>
                                    <div class="panel-body">
                                        `)
		//line api/server/templates/rows.qtpl:329
		for _, action := range child.Actions {
			//line api/server/templates/rows.qtpl:329
			qw422016.N().S(`
                                            <button type="button" class="btn btn-w-m btn-default">`)
			//line api/server/templates/rows.qtpl:330
			qw422016.E().S(action.Title)
			//line api/server/templates/rows.qtpl:330
			qw422016.N().S(`</button>
                                        `)
			//line api/server/templates/rows.qtpl:331
		}
		//line api/server/templates/rows.qtpl:331
		qw422016.N().S(`
                                    </div>
                                </div>
                            </div>
                        `)
		//line api/server/templates/rows.qtpl:335
	}
	//line api/server/templates/rows.qtpl:335
	qw422016.N().S(`
                    </div>
`)
//line api/server/templates/rows.qtpl:337
}

//line api/server/templates/rows.qtpl:337
func (b DeviceBox) WriteHTML(qq422016 qtio422016.Writer) {
	//line api/server/templates/rows.qtpl:337
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line api/server/templates/rows.qtpl:337
	b.StreamHTML(qw422016)
	//line api/server/templates/rows.qtpl:337
	qt422016.ReleaseWriter(qw422016)
//line api/server/templates/rows.qtpl:337
}

//line api/server/templates/rows.qtpl:337
func (b DeviceBox) HTML() string {
	//line api/server/templates/rows.qtpl:337
	qb422016 := qt422016.AcquireByteBuffer()
	//line api/server/templates/rows.qtpl:337
	b.WriteHTML(qb422016)
	//line api/server/templates/rows.qtpl:337
	qs422016 := string(qb422016.B)
	//line api/server/templates/rows.qtpl:337
	qt422016.ReleaseByteBuffer(qb422016)
	//line api/server/templates/rows.qtpl:337
	return qs422016
//line api/server/templates/rows.qtpl:337
}
